#!/bin/bash
# Generates INFO at pack time. PACKAGE_VERSION comes from build-spk.sh.
cat <<EOF
package="pilotserver"
displayname="PilotServer"
displayname_enu="PilotServer"
version="${PACKAGE_VERSION}"
description="Self-hosted OpenPilot/DragonPilot compatible server (API, Athena, upload, OTA)."
description_enu="Self-hosted OpenPilot/DragonPilot compatible server (API, Athena, upload, OTA)."
arch="x86_64"
os_min_ver="7.2-64570"
maintainer="pilotserver"
maintainer_url="https://github.com/local/pilotserver"
distributor="pilotserver"
distributor_url="https://github.com/local/pilotserver"
support_url="https://github.com/local/pilotserver"
helpurl="https://github.com/local/pilotserver"
thirdparty="yes"
install_dep_packages=""
install_type="package"
silent_install="no"
silent_upgrade="yes"
silent_uninstall="no"
reloadui="yes"
startable="yes"
ctl_stop="yes"
adminprotocol="http"
adminurl="/admin/"
adminport="8080"
dsmuidir="ui"
dsmappname="SYNO.SDS.PilotServer.Application"
EOF
