#!/bin/sh
# Common paths for Synology package scripts.
# PACKAGE / PACKAGE_DIR / PACKAGE_VAR etc. are exported by Synology.

PILOTSERVER_HOME="${SYNOPKG_PKGDEST:-/var/packages/pilotserver/target}"
PILOTSERVER_VAR="${SYNOPKG_PKGVAR:-/var/packages/pilotserver/var}"
# DSM7 package user can always write PKGVAR; do not require /volume1 create rights.
PILOTSERVER_DATA_DEFAULT="${PILOTSERVER_VAR}/data"
PILOTSERVER_ENV_FILE="${PILOTSERVER_DATA_DEFAULT}/pilotserver.env"
PILOTSERVER_BIN="${PILOTSERVER_HOME}/bin/pilotserver"
PILOTSERVER_PID="${PILOTSERVER_VAR}/pilotserver.pid"
PILOTSERVER_LOG="${PILOTSERVER_VAR}/pilotserver.log"
PILOTSERVER_INSTALL_LOG="${PILOTSERVER_VAR}/install.log"
