// Code generated by capnpc-go. DO NOT EDIT.

package cereal

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
)

type ControlsStateExt capnp.Struct

// ControlsStateExt_TypeID is the unique identifier for the type ControlsStateExt.
const ControlsStateExt_TypeID = 0x81c2f05a394cf4af

func NewControlsStateExt(s *capnp.Segment) (ControlsStateExt, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return ControlsStateExt(st), err
}

func NewRootControlsStateExt(s *capnp.Segment) (ControlsStateExt, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return ControlsStateExt(st), err
}

func ReadRootControlsStateExt(msg *capnp.Message) (ControlsStateExt, error) {
	root, err := msg.Root()
	return ControlsStateExt(root.Struct()), err
}

func (s ControlsStateExt) String() string {
	str, _ := text.Marshal(0x81c2f05a394cf4af, capnp.Struct(s))
	return str
}

func (s ControlsStateExt) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ControlsStateExt) DecodeFromPtr(p capnp.Ptr) ControlsStateExt {
	return ControlsStateExt(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ControlsStateExt) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ControlsStateExt) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ControlsStateExt) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ControlsStateExt) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ControlsStateExt) AlkaActive() bool {
	return capnp.Struct(s).Bit(0)
}

func (s ControlsStateExt) SetAlkaActive(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// ControlsStateExt_List is a list of ControlsStateExt.
type ControlsStateExt_List = capnp.StructList[ControlsStateExt]

// NewControlsStateExt creates a new list of ControlsStateExt.
func NewControlsStateExt_List(s *capnp.Segment, sz int32) (ControlsStateExt_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[ControlsStateExt](l), err
}

// ControlsStateExt_Future is a wrapper for a ControlsStateExt promised by a client call.
type ControlsStateExt_Future struct{ *capnp.Future }

func (f ControlsStateExt_Future) Struct() (ControlsStateExt, error) {
	p, err := f.Future.Ptr()
	return ControlsStateExt(p.Struct()), err
}

type CarStateExt capnp.Struct

// CarStateExt_TypeID is the unique identifier for the type CarStateExt.
const CarStateExt_TypeID = 0xaedffd8f31e7b55d

func NewCarStateExt(s *capnp.Segment) (CarStateExt, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return CarStateExt(st), err
}

func NewRootCarStateExt(s *capnp.Segment) (CarStateExt, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return CarStateExt(st), err
}

func ReadRootCarStateExt(msg *capnp.Message) (CarStateExt, error) {
	root, err := msg.Root()
	return CarStateExt(root.Struct()), err
}

func (s CarStateExt) String() string {
	str, _ := text.Marshal(0xaedffd8f31e7b55d, capnp.Struct(s))
	return str
}

func (s CarStateExt) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CarStateExt) DecodeFromPtr(p capnp.Ptr) CarStateExt {
	return CarStateExt(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CarStateExt) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CarStateExt) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CarStateExt) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CarStateExt) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CarStateExt) LkasOn() bool {
	return capnp.Struct(s).Bit(0)
}

func (s CarStateExt) SetLkasOn(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// CarStateExt_List is a list of CarStateExt.
type CarStateExt_List = capnp.StructList[CarStateExt]

// NewCarStateExt creates a new list of CarStateExt.
func NewCarStateExt_List(s *capnp.Segment, sz int32) (CarStateExt_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[CarStateExt](l), err
}

// CarStateExt_Future is a wrapper for a CarStateExt promised by a client call.
type CarStateExt_Future struct{ *capnp.Future }

func (f CarStateExt_Future) Struct() (CarStateExt, error) {
	p, err := f.Future.Ptr()
	return CarStateExt(p.Struct()), err
}

type ModelExt capnp.Struct

// ModelExt_TypeID is the unique identifier for the type ModelExt.
const ModelExt_TypeID = 0xf35cc4560bbf6ec2

func NewModelExt(s *capnp.Segment) (ModelExt, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return ModelExt(st), err
}

func NewRootModelExt(s *capnp.Segment) (ModelExt, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return ModelExt(st), err
}

func ReadRootModelExt(msg *capnp.Message) (ModelExt, error) {
	root, err := msg.Root()
	return ModelExt(root.Struct()), err
}

func (s ModelExt) String() string {
	str, _ := text.Marshal(0xf35cc4560bbf6ec2, capnp.Struct(s))
	return str
}

func (s ModelExt) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ModelExt) DecodeFromPtr(p capnp.Ptr) ModelExt {
	return ModelExt(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ModelExt) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ModelExt) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ModelExt) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ModelExt) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ModelExt) LeftEdgeDetected() bool {
	return capnp.Struct(s).Bit(0)
}

func (s ModelExt) SetLeftEdgeDetected(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s ModelExt) RightEdgeDetected() bool {
	return capnp.Struct(s).Bit(1)
}

func (s ModelExt) SetRightEdgeDetected(v bool) {
	capnp.Struct(s).SetBit(1, v)
}

// ModelExt_List is a list of ModelExt.
type ModelExt_List = capnp.StructList[ModelExt]

// NewModelExt creates a new list of ModelExt.
func NewModelExt_List(s *capnp.Segment, sz int32) (ModelExt_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[ModelExt](l), err
}

// ModelExt_Future is a wrapper for a ModelExt promised by a client call.
type ModelExt_Future struct{ *capnp.Future }

func (f ModelExt_Future) Struct() (ModelExt, error) {
	p, err := f.Future.Ptr()
	return ModelExt(p.Struct()), err
}

type DashyState capnp.Struct

// DashyState_TypeID is the unique identifier for the type DashyState.
const DashyState_TypeID = 0xda96579883444c35

func NewDashyState(s *capnp.Segment) (DashyState, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return DashyState(st), err
}

func NewRootDashyState(s *capnp.Segment) (DashyState, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return DashyState(st), err
}

func ReadRootDashyState(msg *capnp.Message) (DashyState, error) {
	root, err := msg.Root()
	return DashyState(root.Struct()), err
}

func (s DashyState) String() string {
	str, _ := text.Marshal(0xda96579883444c35, capnp.Struct(s))
	return str
}

func (s DashyState) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (DashyState) DecodeFromPtr(p capnp.Ptr) DashyState {
	return DashyState(capnp.Struct{}.DecodeFromPtr(p))
}

func (s DashyState) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s DashyState) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s DashyState) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s DashyState) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s DashyState) Json() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s DashyState) HasJson() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s DashyState) SetJson(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// DashyState_List is a list of DashyState.
type DashyState_List = capnp.StructList[DashyState]

// NewDashyState creates a new list of DashyState.
func NewDashyState_List(s *capnp.Segment, sz int32) (DashyState_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[DashyState](l), err
}

// DashyState_Future is a wrapper for a DashyState promised by a client call.
type DashyState_Future struct{ *capnp.Future }

func (f DashyState_Future) Struct() (DashyState, error) {
	p, err := f.Future.Ptr()
	return DashyState(p.Struct()), err
}

type CustomReserved4 capnp.Struct

// CustomReserved4_TypeID is the unique identifier for the type CustomReserved4.
const CustomReserved4_TypeID = 0x80ae746ee2596b11

func NewCustomReserved4(s *capnp.Segment) (CustomReserved4, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved4(st), err
}

func NewRootCustomReserved4(s *capnp.Segment) (CustomReserved4, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved4(st), err
}

func ReadRootCustomReserved4(msg *capnp.Message) (CustomReserved4, error) {
	root, err := msg.Root()
	return CustomReserved4(root.Struct()), err
}

func (s CustomReserved4) String() string {
	str, _ := text.Marshal(0x80ae746ee2596b11, capnp.Struct(s))
	return str
}

func (s CustomReserved4) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved4) DecodeFromPtr(p capnp.Ptr) CustomReserved4 {
	return CustomReserved4(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved4) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved4) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved4) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved4) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved4_List is a list of CustomReserved4.
type CustomReserved4_List = capnp.StructList[CustomReserved4]

// NewCustomReserved4 creates a new list of CustomReserved4.
func NewCustomReserved4_List(s *capnp.Segment, sz int32) (CustomReserved4_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved4](l), err
}

// CustomReserved4_Future is a wrapper for a CustomReserved4 promised by a client call.
type CustomReserved4_Future struct{ *capnp.Future }

func (f CustomReserved4_Future) Struct() (CustomReserved4, error) {
	p, err := f.Future.Ptr()
	return CustomReserved4(p.Struct()), err
}

type CustomReserved5 capnp.Struct

// CustomReserved5_TypeID is the unique identifier for the type CustomReserved5.
const CustomReserved5_TypeID = 0xa5cd762cd951a455

func NewCustomReserved5(s *capnp.Segment) (CustomReserved5, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved5(st), err
}

func NewRootCustomReserved5(s *capnp.Segment) (CustomReserved5, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved5(st), err
}

func ReadRootCustomReserved5(msg *capnp.Message) (CustomReserved5, error) {
	root, err := msg.Root()
	return CustomReserved5(root.Struct()), err
}

func (s CustomReserved5) String() string {
	str, _ := text.Marshal(0xa5cd762cd951a455, capnp.Struct(s))
	return str
}

func (s CustomReserved5) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved5) DecodeFromPtr(p capnp.Ptr) CustomReserved5 {
	return CustomReserved5(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved5) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved5) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved5) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved5) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved5_List is a list of CustomReserved5.
type CustomReserved5_List = capnp.StructList[CustomReserved5]

// NewCustomReserved5 creates a new list of CustomReserved5.
func NewCustomReserved5_List(s *capnp.Segment, sz int32) (CustomReserved5_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved5](l), err
}

// CustomReserved5_Future is a wrapper for a CustomReserved5 promised by a client call.
type CustomReserved5_Future struct{ *capnp.Future }

func (f CustomReserved5_Future) Struct() (CustomReserved5, error) {
	p, err := f.Future.Ptr()
	return CustomReserved5(p.Struct()), err
}

type CustomReserved6 capnp.Struct

// CustomReserved6_TypeID is the unique identifier for the type CustomReserved6.
const CustomReserved6_TypeID = 0xf98d843bfd7004a3

func NewCustomReserved6(s *capnp.Segment) (CustomReserved6, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved6(st), err
}

func NewRootCustomReserved6(s *capnp.Segment) (CustomReserved6, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved6(st), err
}

func ReadRootCustomReserved6(msg *capnp.Message) (CustomReserved6, error) {
	root, err := msg.Root()
	return CustomReserved6(root.Struct()), err
}

func (s CustomReserved6) String() string {
	str, _ := text.Marshal(0xf98d843bfd7004a3, capnp.Struct(s))
	return str
}

func (s CustomReserved6) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved6) DecodeFromPtr(p capnp.Ptr) CustomReserved6 {
	return CustomReserved6(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved6) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved6) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved6) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved6) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved6_List is a list of CustomReserved6.
type CustomReserved6_List = capnp.StructList[CustomReserved6]

// NewCustomReserved6 creates a new list of CustomReserved6.
func NewCustomReserved6_List(s *capnp.Segment, sz int32) (CustomReserved6_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved6](l), err
}

// CustomReserved6_Future is a wrapper for a CustomReserved6 promised by a client call.
type CustomReserved6_Future struct{ *capnp.Future }

func (f CustomReserved6_Future) Struct() (CustomReserved6, error) {
	p, err := f.Future.Ptr()
	return CustomReserved6(p.Struct()), err
}

type CustomReserved7 capnp.Struct

// CustomReserved7_TypeID is the unique identifier for the type CustomReserved7.
const CustomReserved7_TypeID = 0xb86e6369214c01c8

func NewCustomReserved7(s *capnp.Segment) (CustomReserved7, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved7(st), err
}

func NewRootCustomReserved7(s *capnp.Segment) (CustomReserved7, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved7(st), err
}

func ReadRootCustomReserved7(msg *capnp.Message) (CustomReserved7, error) {
	root, err := msg.Root()
	return CustomReserved7(root.Struct()), err
}

func (s CustomReserved7) String() string {
	str, _ := text.Marshal(0xb86e6369214c01c8, capnp.Struct(s))
	return str
}

func (s CustomReserved7) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved7) DecodeFromPtr(p capnp.Ptr) CustomReserved7 {
	return CustomReserved7(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved7) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved7) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved7) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved7) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved7_List is a list of CustomReserved7.
type CustomReserved7_List = capnp.StructList[CustomReserved7]

// NewCustomReserved7 creates a new list of CustomReserved7.
func NewCustomReserved7_List(s *capnp.Segment, sz int32) (CustomReserved7_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved7](l), err
}

// CustomReserved7_Future is a wrapper for a CustomReserved7 promised by a client call.
type CustomReserved7_Future struct{ *capnp.Future }

func (f CustomReserved7_Future) Struct() (CustomReserved7, error) {
	p, err := f.Future.Ptr()
	return CustomReserved7(p.Struct()), err
}

type CustomReserved8 capnp.Struct

// CustomReserved8_TypeID is the unique identifier for the type CustomReserved8.
const CustomReserved8_TypeID = 0xf416ec09499d9d19

func NewCustomReserved8(s *capnp.Segment) (CustomReserved8, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved8(st), err
}

func NewRootCustomReserved8(s *capnp.Segment) (CustomReserved8, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved8(st), err
}

func ReadRootCustomReserved8(msg *capnp.Message) (CustomReserved8, error) {
	root, err := msg.Root()
	return CustomReserved8(root.Struct()), err
}

func (s CustomReserved8) String() string {
	str, _ := text.Marshal(0xf416ec09499d9d19, capnp.Struct(s))
	return str
}

func (s CustomReserved8) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved8) DecodeFromPtr(p capnp.Ptr) CustomReserved8 {
	return CustomReserved8(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved8) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved8) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved8) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved8) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved8_List is a list of CustomReserved8.
type CustomReserved8_List = capnp.StructList[CustomReserved8]

// NewCustomReserved8 creates a new list of CustomReserved8.
func NewCustomReserved8_List(s *capnp.Segment, sz int32) (CustomReserved8_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved8](l), err
}

// CustomReserved8_Future is a wrapper for a CustomReserved8 promised by a client call.
type CustomReserved8_Future struct{ *capnp.Future }

func (f CustomReserved8_Future) Struct() (CustomReserved8, error) {
	p, err := f.Future.Ptr()
	return CustomReserved8(p.Struct()), err
}

type CustomReserved9 capnp.Struct

// CustomReserved9_TypeID is the unique identifier for the type CustomReserved9.
const CustomReserved9_TypeID = 0xa1680744031fdb2d

func NewCustomReserved9(s *capnp.Segment) (CustomReserved9, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved9(st), err
}

func NewRootCustomReserved9(s *capnp.Segment) (CustomReserved9, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved9(st), err
}

func ReadRootCustomReserved9(msg *capnp.Message) (CustomReserved9, error) {
	root, err := msg.Root()
	return CustomReserved9(root.Struct()), err
}

func (s CustomReserved9) String() string {
	str, _ := text.Marshal(0xa1680744031fdb2d, capnp.Struct(s))
	return str
}

func (s CustomReserved9) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved9) DecodeFromPtr(p capnp.Ptr) CustomReserved9 {
	return CustomReserved9(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved9) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved9) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved9) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved9) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved9_List is a list of CustomReserved9.
type CustomReserved9_List = capnp.StructList[CustomReserved9]

// NewCustomReserved9 creates a new list of CustomReserved9.
func NewCustomReserved9_List(s *capnp.Segment, sz int32) (CustomReserved9_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved9](l), err
}

// CustomReserved9_Future is a wrapper for a CustomReserved9 promised by a client call.
type CustomReserved9_Future struct{ *capnp.Future }

func (f CustomReserved9_Future) Struct() (CustomReserved9, error) {
	p, err := f.Future.Ptr()
	return CustomReserved9(p.Struct()), err
}

type CustomReserved10 capnp.Struct

// CustomReserved10_TypeID is the unique identifier for the type CustomReserved10.
const CustomReserved10_TypeID = 0xcb9fd56c7057593a

func NewCustomReserved10(s *capnp.Segment) (CustomReserved10, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved10(st), err
}

func NewRootCustomReserved10(s *capnp.Segment) (CustomReserved10, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved10(st), err
}

func ReadRootCustomReserved10(msg *capnp.Message) (CustomReserved10, error) {
	root, err := msg.Root()
	return CustomReserved10(root.Struct()), err
}

func (s CustomReserved10) String() string {
	str, _ := text.Marshal(0xcb9fd56c7057593a, capnp.Struct(s))
	return str
}

func (s CustomReserved10) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved10) DecodeFromPtr(p capnp.Ptr) CustomReserved10 {
	return CustomReserved10(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved10) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved10) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved10) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved10) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved10_List is a list of CustomReserved10.
type CustomReserved10_List = capnp.StructList[CustomReserved10]

// NewCustomReserved10 creates a new list of CustomReserved10.
func NewCustomReserved10_List(s *capnp.Segment, sz int32) (CustomReserved10_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved10](l), err
}

// CustomReserved10_Future is a wrapper for a CustomReserved10 promised by a client call.
type CustomReserved10_Future struct{ *capnp.Future }

func (f CustomReserved10_Future) Struct() (CustomReserved10, error) {
	p, err := f.Future.Ptr()
	return CustomReserved10(p.Struct()), err
}

type CustomReserved11 capnp.Struct

// CustomReserved11_TypeID is the unique identifier for the type CustomReserved11.
const CustomReserved11_TypeID = 0xc2243c65e0340384

func NewCustomReserved11(s *capnp.Segment) (CustomReserved11, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved11(st), err
}

func NewRootCustomReserved11(s *capnp.Segment) (CustomReserved11, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved11(st), err
}

func ReadRootCustomReserved11(msg *capnp.Message) (CustomReserved11, error) {
	root, err := msg.Root()
	return CustomReserved11(root.Struct()), err
}

func (s CustomReserved11) String() string {
	str, _ := text.Marshal(0xc2243c65e0340384, capnp.Struct(s))
	return str
}

func (s CustomReserved11) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved11) DecodeFromPtr(p capnp.Ptr) CustomReserved11 {
	return CustomReserved11(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved11) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved11) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved11) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved11) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved11_List is a list of CustomReserved11.
type CustomReserved11_List = capnp.StructList[CustomReserved11]

// NewCustomReserved11 creates a new list of CustomReserved11.
func NewCustomReserved11_List(s *capnp.Segment, sz int32) (CustomReserved11_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved11](l), err
}

// CustomReserved11_Future is a wrapper for a CustomReserved11 promised by a client call.
type CustomReserved11_Future struct{ *capnp.Future }

func (f CustomReserved11_Future) Struct() (CustomReserved11, error) {
	p, err := f.Future.Ptr()
	return CustomReserved11(p.Struct()), err
}

type CustomReserved12 capnp.Struct

// CustomReserved12_TypeID is the unique identifier for the type CustomReserved12.
const CustomReserved12_TypeID = 0x9ccdc8676701b412

func NewCustomReserved12(s *capnp.Segment) (CustomReserved12, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved12(st), err
}

func NewRootCustomReserved12(s *capnp.Segment) (CustomReserved12, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved12(st), err
}

func ReadRootCustomReserved12(msg *capnp.Message) (CustomReserved12, error) {
	root, err := msg.Root()
	return CustomReserved12(root.Struct()), err
}

func (s CustomReserved12) String() string {
	str, _ := text.Marshal(0x9ccdc8676701b412, capnp.Struct(s))
	return str
}

func (s CustomReserved12) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved12) DecodeFromPtr(p capnp.Ptr) CustomReserved12 {
	return CustomReserved12(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved12) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved12) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved12) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved12) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved12_List is a list of CustomReserved12.
type CustomReserved12_List = capnp.StructList[CustomReserved12]

// NewCustomReserved12 creates a new list of CustomReserved12.
func NewCustomReserved12_List(s *capnp.Segment, sz int32) (CustomReserved12_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved12](l), err
}

// CustomReserved12_Future is a wrapper for a CustomReserved12 promised by a client call.
type CustomReserved12_Future struct{ *capnp.Future }

func (f CustomReserved12_Future) Struct() (CustomReserved12, error) {
	p, err := f.Future.Ptr()
	return CustomReserved12(p.Struct()), err
}

type CustomReserved13 capnp.Struct

// CustomReserved13_TypeID is the unique identifier for the type CustomReserved13.
const CustomReserved13_TypeID = 0xcd96dafb67a082d0

func NewCustomReserved13(s *capnp.Segment) (CustomReserved13, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved13(st), err
}

func NewRootCustomReserved13(s *capnp.Segment) (CustomReserved13, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved13(st), err
}

func ReadRootCustomReserved13(msg *capnp.Message) (CustomReserved13, error) {
	root, err := msg.Root()
	return CustomReserved13(root.Struct()), err
}

func (s CustomReserved13) String() string {
	str, _ := text.Marshal(0xcd96dafb67a082d0, capnp.Struct(s))
	return str
}

func (s CustomReserved13) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved13) DecodeFromPtr(p capnp.Ptr) CustomReserved13 {
	return CustomReserved13(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved13) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved13) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved13) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved13) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved13_List is a list of CustomReserved13.
type CustomReserved13_List = capnp.StructList[CustomReserved13]

// NewCustomReserved13 creates a new list of CustomReserved13.
func NewCustomReserved13_List(s *capnp.Segment, sz int32) (CustomReserved13_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved13](l), err
}

// CustomReserved13_Future is a wrapper for a CustomReserved13 promised by a client call.
type CustomReserved13_Future struct{ *capnp.Future }

func (f CustomReserved13_Future) Struct() (CustomReserved13, error) {
	p, err := f.Future.Ptr()
	return CustomReserved13(p.Struct()), err
}

type CustomReserved14 capnp.Struct

// CustomReserved14_TypeID is the unique identifier for the type CustomReserved14.
const CustomReserved14_TypeID = 0xb057204d7deadf3f

func NewCustomReserved14(s *capnp.Segment) (CustomReserved14, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved14(st), err
}

func NewRootCustomReserved14(s *capnp.Segment) (CustomReserved14, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved14(st), err
}

func ReadRootCustomReserved14(msg *capnp.Message) (CustomReserved14, error) {
	root, err := msg.Root()
	return CustomReserved14(root.Struct()), err
}

func (s CustomReserved14) String() string {
	str, _ := text.Marshal(0xb057204d7deadf3f, capnp.Struct(s))
	return str
}

func (s CustomReserved14) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved14) DecodeFromPtr(p capnp.Ptr) CustomReserved14 {
	return CustomReserved14(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved14) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved14) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved14) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved14) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved14_List is a list of CustomReserved14.
type CustomReserved14_List = capnp.StructList[CustomReserved14]

// NewCustomReserved14 creates a new list of CustomReserved14.
func NewCustomReserved14_List(s *capnp.Segment, sz int32) (CustomReserved14_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved14](l), err
}

// CustomReserved14_Future is a wrapper for a CustomReserved14 promised by a client call.
type CustomReserved14_Future struct{ *capnp.Future }

func (f CustomReserved14_Future) Struct() (CustomReserved14, error) {
	p, err := f.Future.Ptr()
	return CustomReserved14(p.Struct()), err
}

type CustomReserved15 capnp.Struct

// CustomReserved15_TypeID is the unique identifier for the type CustomReserved15.
const CustomReserved15_TypeID = 0xbd443b539493bc68

func NewCustomReserved15(s *capnp.Segment) (CustomReserved15, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved15(st), err
}

func NewRootCustomReserved15(s *capnp.Segment) (CustomReserved15, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved15(st), err
}

func ReadRootCustomReserved15(msg *capnp.Message) (CustomReserved15, error) {
	root, err := msg.Root()
	return CustomReserved15(root.Struct()), err
}

func (s CustomReserved15) String() string {
	str, _ := text.Marshal(0xbd443b539493bc68, capnp.Struct(s))
	return str
}

func (s CustomReserved15) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved15) DecodeFromPtr(p capnp.Ptr) CustomReserved15 {
	return CustomReserved15(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved15) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved15) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved15) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved15) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved15_List is a list of CustomReserved15.
type CustomReserved15_List = capnp.StructList[CustomReserved15]

// NewCustomReserved15 creates a new list of CustomReserved15.
func NewCustomReserved15_List(s *capnp.Segment, sz int32) (CustomReserved15_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved15](l), err
}

// CustomReserved15_Future is a wrapper for a CustomReserved15 promised by a client call.
type CustomReserved15_Future struct{ *capnp.Future }

func (f CustomReserved15_Future) Struct() (CustomReserved15, error) {
	p, err := f.Future.Ptr()
	return CustomReserved15(p.Struct()), err
}

type CustomReserved16 capnp.Struct

// CustomReserved16_TypeID is the unique identifier for the type CustomReserved16.
const CustomReserved16_TypeID = 0xfc6241ed8877b611

func NewCustomReserved16(s *capnp.Segment) (CustomReserved16, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved16(st), err
}

func NewRootCustomReserved16(s *capnp.Segment) (CustomReserved16, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved16(st), err
}

func ReadRootCustomReserved16(msg *capnp.Message) (CustomReserved16, error) {
	root, err := msg.Root()
	return CustomReserved16(root.Struct()), err
}

func (s CustomReserved16) String() string {
	str, _ := text.Marshal(0xfc6241ed8877b611, capnp.Struct(s))
	return str
}

func (s CustomReserved16) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved16) DecodeFromPtr(p capnp.Ptr) CustomReserved16 {
	return CustomReserved16(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved16) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved16) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved16) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved16) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved16_List is a list of CustomReserved16.
type CustomReserved16_List = capnp.StructList[CustomReserved16]

// NewCustomReserved16 creates a new list of CustomReserved16.
func NewCustomReserved16_List(s *capnp.Segment, sz int32) (CustomReserved16_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved16](l), err
}

// CustomReserved16_Future is a wrapper for a CustomReserved16 promised by a client call.
type CustomReserved16_Future struct{ *capnp.Future }

func (f CustomReserved16_Future) Struct() (CustomReserved16, error) {
	p, err := f.Future.Ptr()
	return CustomReserved16(p.Struct()), err
}

type CustomReserved17 capnp.Struct

// CustomReserved17_TypeID is the unique identifier for the type CustomReserved17.
const CustomReserved17_TypeID = 0xa30662f84033036c

func NewCustomReserved17(s *capnp.Segment) (CustomReserved17, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved17(st), err
}

func NewRootCustomReserved17(s *capnp.Segment) (CustomReserved17, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved17(st), err
}

func ReadRootCustomReserved17(msg *capnp.Message) (CustomReserved17, error) {
	root, err := msg.Root()
	return CustomReserved17(root.Struct()), err
}

func (s CustomReserved17) String() string {
	str, _ := text.Marshal(0xa30662f84033036c, capnp.Struct(s))
	return str
}

func (s CustomReserved17) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved17) DecodeFromPtr(p capnp.Ptr) CustomReserved17 {
	return CustomReserved17(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved17) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved17) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved17) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved17) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved17_List is a list of CustomReserved17.
type CustomReserved17_List = capnp.StructList[CustomReserved17]

// NewCustomReserved17 creates a new list of CustomReserved17.
func NewCustomReserved17_List(s *capnp.Segment, sz int32) (CustomReserved17_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved17](l), err
}

// CustomReserved17_Future is a wrapper for a CustomReserved17 promised by a client call.
type CustomReserved17_Future struct{ *capnp.Future }

func (f CustomReserved17_Future) Struct() (CustomReserved17, error) {
	p, err := f.Future.Ptr()
	return CustomReserved17(p.Struct()), err
}

type CustomReserved18 capnp.Struct

// CustomReserved18_TypeID is the unique identifier for the type CustomReserved18.
const CustomReserved18_TypeID = 0xc86a3d38d13eb3ef

func NewCustomReserved18(s *capnp.Segment) (CustomReserved18, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved18(st), err
}

func NewRootCustomReserved18(s *capnp.Segment) (CustomReserved18, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved18(st), err
}

func ReadRootCustomReserved18(msg *capnp.Message) (CustomReserved18, error) {
	root, err := msg.Root()
	return CustomReserved18(root.Struct()), err
}

func (s CustomReserved18) String() string {
	str, _ := text.Marshal(0xc86a3d38d13eb3ef, capnp.Struct(s))
	return str
}

func (s CustomReserved18) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved18) DecodeFromPtr(p capnp.Ptr) CustomReserved18 {
	return CustomReserved18(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved18) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved18) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved18) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved18) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved18_List is a list of CustomReserved18.
type CustomReserved18_List = capnp.StructList[CustomReserved18]

// NewCustomReserved18 creates a new list of CustomReserved18.
func NewCustomReserved18_List(s *capnp.Segment, sz int32) (CustomReserved18_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved18](l), err
}

// CustomReserved18_Future is a wrapper for a CustomReserved18 promised by a client call.
type CustomReserved18_Future struct{ *capnp.Future }

func (f CustomReserved18_Future) Struct() (CustomReserved18, error) {
	p, err := f.Future.Ptr()
	return CustomReserved18(p.Struct()), err
}

type CustomReserved19 capnp.Struct

// CustomReserved19_TypeID is the unique identifier for the type CustomReserved19.
const CustomReserved19_TypeID = 0xa4f1eb3323f5f582

func NewCustomReserved19(s *capnp.Segment) (CustomReserved19, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved19(st), err
}

func NewRootCustomReserved19(s *capnp.Segment) (CustomReserved19, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return CustomReserved19(st), err
}

func ReadRootCustomReserved19(msg *capnp.Message) (CustomReserved19, error) {
	root, err := msg.Root()
	return CustomReserved19(root.Struct()), err
}

func (s CustomReserved19) String() string {
	str, _ := text.Marshal(0xa4f1eb3323f5f582, capnp.Struct(s))
	return str
}

func (s CustomReserved19) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CustomReserved19) DecodeFromPtr(p capnp.Ptr) CustomReserved19 {
	return CustomReserved19(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CustomReserved19) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CustomReserved19) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CustomReserved19) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CustomReserved19) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// CustomReserved19_List is a list of CustomReserved19.
type CustomReserved19_List = capnp.StructList[CustomReserved19]

// NewCustomReserved19 creates a new list of CustomReserved19.
func NewCustomReserved19_List(s *capnp.Segment, sz int32) (CustomReserved19_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[CustomReserved19](l), err
}

// CustomReserved19_Future is a wrapper for a CustomReserved19 promised by a client call.
type CustomReserved19_Future struct{ *capnp.Future }

func (f CustomReserved19_Future) Struct() (CustomReserved19, error) {
	p, err := f.Future.Ptr()
	return CustomReserved19(p.Struct()), err
}
