#!/bin/sh
set -eu

dir=$(CDPATH= cd "$(dirname "$0")" && pwd)
repo_root=$(CDPATH= cd "$dir/../../.." && pwd)

if ! command -v capnp >/dev/null 2>&1; then
	echo "generate.sh: capnp is required" >&2
	exit 1
fi
if ! command -v capnpc-go >/dev/null 2>&1; then
	echo "generate.sh: capnpc-go is required" >&2
	exit 1
fi

module_dir=$(cd "$repo_root" && go list -m -f '{{.Dir}}' capnproto.org/go/capnp/v3)
go_include="$module_dir/std"
if [ ! -f "$go_include/go.capnp" ]; then
	echo "generate.sh: go.capnp not found in pinned Go module" >&2
	exit 1
fi

tmp=$(mktemp -d "${TMPDIR:-/tmp}/pilotserver-cereal.XXXXXX")
trap 'rm -rf "$tmp"; rm -f "$dir"/.*.capnp.go.tmp.$$' EXIT HUP INT TERM
mkdir -p "$tmp/schema/include" "$tmp/output"

annotate() {
	source=$1
	target=$2
	{
		printf '%s\n' \
			'using Go = import "/go.capnp";' \
			'$Go.package("cereal");' \
			'$Go.import("pilotserver/internal/replay/cereal");' \
			''
		cat "$source"
	} >"$target"
}

annotate "$dir/schema/log.capnp" "$tmp/schema/log.capnp"
annotate "$dir/schema/car.capnp" "$tmp/schema/car.capnp"
annotate "$dir/schema/custom.capnp" "$tmp/schema/custom.capnp"
annotate "$dir/schema/deprecated.capnp" "$tmp/schema/deprecated.capnp"
annotate "$dir/schema/include/c++.capnp" "$tmp/schema/include/c++.capnp"

capnp compile \
	--src-prefix "$tmp/schema" \
	-I "$tmp/schema" \
	-I "$go_include" \
	-o "go:$tmp/output" \
	"$tmp/schema/log.capnp" \
	"$tmp/schema/car.capnp" \
	"$tmp/schema/custom.capnp" \
	"$tmp/schema/deprecated.capnp"

for name in log car custom deprecated; do
	output="$tmp/output/$name.capnp.go"
	if [ ! -s "$output" ]; then
		echo "generate.sh: missing or empty generated file: $name.capnp.go" >&2
		exit 1
	fi
	IFS= read -r marker <"$output"
	if [ "$marker" != '// Code generated by capnpc-go. DO NOT EDIT.' ]; then
		echo "generate.sh: missing generated marker: $name.capnp.go" >&2
		exit 1
	fi
done

generated_count=$(find "$tmp/output" -type f -name '*.capnp.go' -print | wc -l | tr -d ' ')
if [ "$generated_count" -ne 4 ]; then
	echo "generate.sh: expected exactly 4 generated files, found $generated_count" >&2
	exit 1
fi

for name in log car custom deprecated; do
	cp "$tmp/output/$name.capnp.go" "$dir/.$name.capnp.go.tmp.$$"
done
for name in log car custom deprecated; do
	mv "$dir/.$name.capnp.go.tmp.$$" "$dir/$name.capnp.go"
done
